/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "bizcondk-nero": "#fff",
        "bizcondk-scorpion": "#5f5f5f",
        "bizcondk-pale-sky": "#69727d",
        "bizcondk-oslo-gray": "#818a91",
        "bizcondk-black": "#000",
        "bizcondk-iron": "#d9dde1",
        "bizcondk-cloud-burst": "#203b54",
        "bizcondk-iron1": "#cfd2d8",
        gray: "rgba(255, 255, 255, 0.89)",
        "bizcondk-gallery": "#eee",
        "bizcondk-alto": "#ddd",
        "bizcondk-big-stone": "#162739",
        "bizcondk-ebony": "#05060b",
        "bizcondk-black-80": "rgba(0, 0, 0, 0.8)",
        "bizcondk-nero-37": "rgba(255, 255, 255, 0.37)",
        "bizcondk-nero-60": "rgba(255, 255, 255, 0.6)",
        "bizcondk-boulder": "#747474",
        red: "#ff0000",
        "bizcondk-alabaster": "#fafafa",
        "bizcondk-mercury": "#eaeaea",
        gainsboro: "rgba(217, 217, 217, 0)",
        "bizcondk-black-65": "rgba(0, 0, 0, 0.65)",
        "bizcondk-mine-shaft": "#333",
        "bizcondk-japanese-laurel": "#ff800f",
      },
      spacing: {},
      fontFamily: {
        "bizcondk-alegreya-sans-light-13": "'Alegreya Sans'",
        "bizcondk-roboto-light-13": "Roboto",
        "bizcondk-inter-medium-24-title": "Inter",
        "red-hat-display": "'Red Hat Display'",
        "font-awesome-5-free": "'Font Awesome 5 Free'",
        "font-awesome-5-brands": "'Font Awesome 5 Brands'",
      },
      borderRadius: {
        "10xs": "3px",
        "6xl": "25px",
        xl: "20px",
        "13xl-3": "32.3px",
        "8xs": "5px",
      },
    },
    fontSize: {
      mini: "0.94rem",
      base: "1rem",
      xl: "1.25rem",
      sm: "0.88rem",
      "13xl": "2rem",
      "5xl": "1.5rem",
      "25xl": "2.75rem",
      lg: "1.13rem",
      "31xl": "3.13rem",
      "5xs": "0.5rem",
      xs: "0.75rem",
      "21xl": "2.5rem",
      "2xl": "1.31rem",
      "46xl": "4.06rem",
      "29xl": "3rem",
      "16xl": "2.19rem",
      "3xs": "0.63rem",
      "3xl": "1.38rem",
      smi: "0.81rem",
      "11xl": "1.88rem",
      "20xl": "2.44rem",
      inherit: "inherit",
    },
  },
  corePlugins: {
    preflight: false,
  },
};
